baseURL = 'https://brokenbluesrepairs.com/'
languageCode = 'en-us'
title = 'Broken Blues Repairs'
theme = 'roxo'
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 1
  [[menu.nav]]
    name    = "How It Works"
    url     = "how-it-works"
    weight  = 2
  [[menu.nav]]
    name    = "Pricing"
    url     = "blog"
    weight  = 3
  [[menu.nav]]
    name    = "Past Repairs"
    url     = "portfolio"
    weight  = 4
  [[menu.nav]]
    name    = "Contact"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "14 FEB 2022"
  # Meta data
  description = "Local repair shop | small appliances and consumer electronics"
  author = "Peter Vieira"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"
  # Google Analitycs
  googleAnalitycsID = "Your ID"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_contact_type      = "Contact Type"
    placeholder_about_the_project = "What's up?"
    send_message                  = "Send Message"

    [[params.contactForm.contactType]]
      value = "re"
      title  = "Repair"
    [[params.contactForm.contactType]]
      value = "pr"
      title  = "Past Repair"
    [[params.contactForm.contactType]]
      value = "do"
      title  = "Donations"
    [[params.contactForm.contactType]]
      value = "qu"
      title  = "Question"
    [[params.contactForm.contactType]]
      value = "co"
      title  = "Comment"

  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Contact"
    url     = "contact"

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "A Local Repair Shop That Focuses on Repairs, Not Profits"
    tagline               = "REDUCING WASTE, ONE BROKEN ITEM AT A TIME"
    primary_button        = "How it works"
    primary_button_url    = "how-it-works"
    secondary_button      = "Connect With Us"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "MY RECENT REPAIRS"
    subtitle  = "Helping people toss less, spend less, and learn more."

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LETâ€™S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "713 Elmwood St.<br>Tucson, AZ 85755"
      phone   = "213-204-0067"
      email   = "info@brokenbluesrepairs.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Repairs"
          url  = "repairs"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Nextdoor"
          url  = "#"
        [[params.footer.social.link]]
          name = "LinkedIn"
          url  = "https://www.linkedin.com/in/peter-vieira-57667624"
        [[params.footer.social.link]]
          name = "Facebook"
          url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "We help you:"
        description = "get rid of those broken blues"